### ISSUE TITLE
Вопросы по лабораторной работе №5

### ISSUE THREAD

**Issue by Doshinsky** [Doshinsky/Lab-5#1]
1. Какие тесты должны быть использованы в данной работе?

2. По поводу оформления проекта: данный проект так же должен быть многофайловым приложением и использовать пользовательскую библиотеку с функциями?

3. Всего должно быть три ветки? (Основная ветка; ветка с коммитами, где мы переделали код; третья ветка, где мы покрываем проект unit-тестами)

@evgeny-p

**Comment by evgeny-p** [comment]
Обсудили устно на паре, краткое резюме:

1. Суть работы в подготовке тестовых данных. Базовые методы: выделение классов эквивалентности и граничных значений.

1. При хранении кода в единственном файле не будет возможности отделить вычислительные функции для их линковки с тестами.

1. Для каждой задачи создается новая ветка. После выполнения задачи ветка мержится в мастер. Одну лабораторную можно считать одной задачей.

Поскольку эта работа базируется на второй, то можно выполнять ее в соответствующем репозитории.
