### ISSUE TITLE
Лабораторная работа #5

### ISSUE THREAD

**Issue by Doshinsky** [Doshinsky/Lab-5#2]
Выполнили:
Дощинский Илья Владиславович
Копылова Елена Витальевна

@evgeny-p

**Comment by Doshinsky** [comment]
Я правильно понимаю, что двойки за к/с нам уже не видать, если даже эта лаба будет идеально сделана и не потребуются исправления и доработки? :с

@evgeny-p

**Comment by evgeny-p** [comment]
В субботу, воскресенье и понедельник был недоступен, последняя работа была принята в пятницу, около 12am, что само по себе не очень.

За выходные получил большое количество уведомлений, проверяю в рабочем порядке. До этой работы пока не добрался.

**Comment by Doshinsky** [comment]
Решил сделать еще пару тестов, после коммитов решил не заливать на гит, а перепроверить всё на следующий день. И тут произошло вот это:
![Image](https://cloud.githubusercontent.com/assets/17213440/14164803/b50776d8-f724-11e5-9872-304979c0c968.png)

Из-за чего это могло произойти и что теперь лучше всего делать?

**Comment by evgeny-p** [comment]
Сложно сказать, почему побились файлы в репозитории. Самое простое решение сейчас: забекапить существующий репозиторий, склонировать новый и перенести файлы из старого репозитория в новый. Коммиты придется создавать заново, но хотя бы изменения не потеряются.

По выполнению работы.

Текущая декомпозиция не очень удобная как в использовании, так и для покрытия тестами.

Если рассматривать функции `discriminant` и `roots` как библиотечные, то они имеют следующие недостатки.

1. Эти функции обязывают клиента реализовывать часть логики по принятию решения относительно корней. Эта логика не покрыта тестами.
1. Предоставленный интерфейс легко использовать неправильно:
  1. Функция `roots` имеет неявную зависимость от клиентского кода и от функции `discriminant`. Она предполагает, что аргументы `a`, `b` и `c` будут те же, что и для функции `discriminant`.
  1. Также имеется предположение, что значение аргумент `d` будет равно возвращаемому значению функции `discriminant` от тех же аргументов.
  1. Предполагается, что `d >= 0`.

  Проще говоря, логически функции имеют сильную связность, но реализация ее нарушает.

Проблема не проявила себя из-за неполного покрытия кода тестами. Достаточно вызвать функцию `roots` с нулями в качестве всех аргументов, чтобы добиться падения приложения.

**Comment by Doshinsky** [comment]
Переделано, залито.

@evgeny-p

**Comment by evgeny-p** [comment]
Принято.

Но форматирование странное. Условные блоки написаны с явно лишними отступами: https://github.com/Doshinsky/Lab-5/blob/master/Source/equation.c
